---
- name: azure cli import repo key
  shell: "rpm --import https://packages.microsoft.com/keys/microsoft.asc"
#- name: azure create local azure cli repo information
#  shell: "sh -c 'echo -e \"[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc\" > /etc/yum.repos.d/azure-cli.repo'"
- name: azure cli add yum repo
  yum_repository:
    name: "Azure-CLI"
    description: "Repository for Azure CLI"
    baseurl: "https://packages.microsoft.com/yumrepos/azure-cli"
    gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
    gpgcheck: yes
- name: azure cli install azure cli
  yum:
    name: "azure-cli"
    state: "present"
