---
postgresql_remote_access_line_regexp: "listen_addresses="
postgresql_remote_access_line_replace: "listen_addresses='*'"

postgresql_pg_hba_users:
    - { type: "local", database: "all", user: "postgres", address: ~, method: "peer" }
    - { type: "host", database: "all", user: "all", address: "0.0.0.0/0", method: "md5" }
    - { type: "host", database: "all", user: "all", address: "::1/0", method: "md5" }

postgresql_databases: []

postgresql_users: []
